# Generated by Django 5.1.7 on 2025-04-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_customerorder_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupenCode',
        ),
    ]
